# Generated by Django 5.2.17 on 2026-09-17 05:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or brief description of the expense', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in currency (must be > 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0.')])),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Bills', 'Bills'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], help_text='Category of the expense', max_length=50)),
                ('date', models.DateField(help_text='Date when the expense was incurred')),
                ('description', models.TextField(blank=True, default='', help_text='Optional additional notes or details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
